backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "building"
    label: "Будівництво"
    folder: "src/content/building"
    create: true
    sortable_fields: ["title", "created"]
    fields:
      - { label: "Заголовок", name: "title", widget: "string", required: true }
      - { label: "Опис", name: "description", widget: "text", required: true }
      - {
          label: "Дата публікації",
          hide: false,
          name: "date",
          widget: "datetime",
          default: "now",
          required: true,
        }
      - {
          label: "Зображення",
          name: "thumbnail",
          widget: "image",
          required: true,
        }
      - {
          label: "Контент",
          name: "body",
          required: true,
          widget: "markdown",
          minimal: true,
          modes: ["rich_text"],
          buttons:
            [
              "bold",
              "italic",
              "code",
              "link",
              "heading-two",
              "heading-three",
              "heading-four",
              "heading-five",
              "heading-six",
              "quote",
              "bulleted-list",
              "numbered-list",
            ],
        }
